Print usage message for binary, handle invalid JSON.

diff --git a/test-files/test b/test-files/test
--- a/test-files/test
+++ b/test-files/test
@@ -41,3 +41,45 @@ else
   diff <(echo "$EXPECTED_IAM") <(echo "$ACTUAL_IAM")
   exit 1
 fi
+
+printf 'Testing JSON to IAM with invalid JSON... '
+
+EXPECTED_ERROR='Invalid JSON!'
+ACTUAL_ERROR=$(./src/cogito to-iam '{' 2>&1)
+
+if [ "$EXPECTED_ERROR" == "$ACTUAL_ERROR" ]; then
+  printf 'Passed.\n\n'
+else
+  echo ''
+  printf '=%.0s' {1..100}
+  printf '\nExpected:\n'
+  echo "$EXPECTED_ERROR"
+  printf '=%.0s' {1..100}
+  printf '\nActual:\n'
+  echo "$ACTUAL_ERROR"
+  printf '=%.0s' {1..100}
+  printf '\nDiff:\n'
+  diff <(echo "$EXPECTED_ERROR") <(echo "$ACTUAL_ERROR")
+  exit 1
+fi
+
+printf 'Testing JSON to IAM with invalid JSON... '
+
+EXPECTED_MSG='USAGE: cogito <to-json|to-iam> <text>'
+ACTUAL_MSG=$(./src/cogito foo 2>&1)
+
+if [ "$EXPECTED_MSG" == "$ACTUAL_MSG" ]; then
+  printf 'Passed.\n\n'
+else
+  echo ''
+  printf '=%.0s' {1..100}
+  printf '\nExpected:\n'
+  echo "$EXPECTED_MSG"
+  printf '=%.0s' {1..100}
+  printf '\nActual:\n'
+  echo "$ACTUAL_MSG"
+  printf '=%.0s' {1..100}
+  printf '\nDiff:\n'
+  diff <(echo "$EXPECTED_MSG") <(echo "$ACTUAL_MSG")
+  exit 1
+fi
